package de.renebergelt.maven.plugins.compileswitches;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a generated java fiel which contains switches
 * @author berre
 */
public class SwitchesFile {

	List<Field> fields = new ArrayList<>();
	
	private String packageName;
	private String className;
	
	private String nl = System.lineSeparator();
	
	public SwitchesFile(String packageName, String className, List<Field> fields) {
		this.packageName = packageName;
		this.className = className;	
		
		this.fields = fields;
	}
	
	public void save(String filename) throws IOException {
		try(FileWriter writer = new FileWriter(filename)) {
			writer.write("package " + packageName + ";" + nl);
			writer.write(nl);
			writer.write("/**" + nl);
			writer.write(" * generated by compile-switches-maven-plugin" + nl);
			writer.write(" */" + nl);
			writer.write("public class " + className + "{" + nl);
			writer.write(nl);
			writeFields(writer);
			writer.write(nl);
			writePrivateConstructor(writer);
			writer.write(nl);
			writer.write("}");
		}
	}
	
	private void writeFields(FileWriter writer) throws IOException {
		for(Field f: fields) {
			writer.write("public static final boolean " + f.fieldName + " = " + String.valueOf(f.fieldValue) + ";" + nl);
		}
	}
	
	private void writePrivateConstructor(FileWriter writer) throws IOException {
		writer.write("private " + className + "() {}" + nl);
	}
	
}
